apiVersion: trading.spectra.fund/v1beta1
kind: Machine
metadata:
  name: infraserver-aliyun-cc-1002
  labels:
    acquisition-type: purchased
    env: dev
spec:
  status: Ready
  connection:
    init: "47.239.53.129:3351"
  provider: "xxx"
  defaultConfigurations:
    - name: server
      value: key
